import Foundation

// MARK: - PartnerSharingServiceProtocol

protocol PartnerSharingServiceProtocol {
    /// Generates a new 6-character alphanumeric share code.
    func generateShareCode() -> String

    /// Returns true when `code` matches the format of a valid BloomHer share code.
    func validateShareCode(_ code: String) -> Bool

    /// Stores a PartnerShare record locally and returns the persistent share code.
    /// In Phase 1 this is local-only (same device, partner mode).
    func activateSharing(partnerName: String?) -> PartnerShareSession

    /// Deactivates an existing share session.
    func deactivateSharing(sessionID: String)

    /// Retrieves all active local share sessions.
    func fetchActiveSessions() -> [PartnerShareSession]

    /// Joins an existing share session using the code generated by the sharing partner.
    /// Returns the session if found and valid, nil otherwise.
    func joinWithCode(_ code: String) -> PartnerShareSession?
}

// MARK: - PartnerShareSession

/// A lightweight value type representing a local partner-sharing session.
/// Persisted to UserDefaults as JSON.  In a future server-connected phase this
/// would be replaced by a backend-managed record.
struct PartnerShareSession: Codable, Identifiable {
    let id: String
    let shareCode: String
    let partnerName: String?
    let createdAt: Date
    var isActive: Bool
}

// MARK: - PartnerSharingService

/// Phase-1 implementation of partner sharing.
///
/// All data is stored locally via `UserDefaults`.  No networking occurs.
/// The share code is designed to be human-readable and transferable via
/// the system share sheet or direct conversation.
///
/// Code format: 6 characters, uppercase letters A–Z and digits 2–9
/// (vowels and visually-ambiguous digits 0/1 are excluded to prevent
/// confusion when sharing verbally or in writing).
final class PartnerSharingService: PartnerSharingServiceProtocol {

    // MARK: - Constants

    private static let codeAlphabet: [Character] = Array("BCDFGHJKLMNPQRSTVWXYZ23456789")
    private static let codeLength: Int = 6
    private static let sessionStorageKey = "bloomher.partnerSessions"

    // MARK: - Code Generation

    func generateShareCode() -> String {
        String((0..<Self.codeLength).map { _ in
            Self.codeAlphabet.randomElement() ?? "B"
        })
    }

    // MARK: - Validation

    func validateShareCode(_ code: String) -> Bool {
        let trimmed = code.trimmingCharacters(in: .whitespacesAndNewlines).uppercased()
        guard trimmed.count == Self.codeLength else { return false }
        // Every character must appear in the allowed alphabet.
        return trimmed.allSatisfy { Self.codeAlphabet.contains($0) }
    }

    // MARK: - Session Management

    func activateSharing(partnerName: String?) -> PartnerShareSession {
        let session = PartnerShareSession(
            id:          UUID().uuidString,
            shareCode:   generateShareCode(),
            partnerName: partnerName,
            createdAt:   Date(),
            isActive:    true
        )
        var sessions = loadSessions()
        sessions.append(session)
        saveSessions(sessions)
        return session
    }

    func deactivateSharing(sessionID: String) {
        var sessions = loadSessions()
        if let index = sessions.firstIndex(where: { $0.id == sessionID }) {
            sessions[index].isActive = false
        }
        saveSessions(sessions)
    }

    func fetchActiveSessions() -> [PartnerShareSession] {
        loadSessions().filter { $0.isActive }
    }

    func joinWithCode(_ code: String) -> PartnerShareSession? {
        let trimmed = code.trimmingCharacters(in: .whitespacesAndNewlines).uppercased()
        guard validateShareCode(trimmed) else { return nil }
        let sessions = loadSessions()
        guard let existing = sessions.first(where: { $0.isActive && $0.shareCode == trimmed }) else {
            return nil
        }
        return existing
    }

    // MARK: - Persistence

    private func loadSessions() -> [PartnerShareSession] {
        guard let data = UserDefaults.standard.data(forKey: Self.sessionStorageKey),
              let sessions = try? JSONDecoder().decode([PartnerShareSession].self, from: data)
        else { return [] }
        return sessions
    }

    private func saveSessions(_ sessions: [PartnerShareSession]) {
        guard let data = try? JSONEncoder().encode(sessions) else { return }
        UserDefaults.standard.set(data, forKey: Self.sessionStorageKey)
    }
}
